version: '3.8'
services:
  backend:
    build: ./api
    ports:
      - "8001:80"
    # environment:
    #   - SOME_BACKEND_ENV_VAR=value # Example environment variable for backend

  frontend:
    build: ./ui
    ports:
      - "3000:3000"
    environment:
      - CHOKIDAR_USEPOLLING=true # Helps with hot-reloading on some systems
